### ISSUE TITLE
main.css

### ISSUE THREAD

**Issue by gburrows** [zachary-kuhn/messages-example#1]
Hi Zach,

Just working my way through your React tutorials. These are very well explained, thank you.

However, when coming over to Github to grab the main.css for the message-example, it seems that you committed the hello-world app to this repo. Any chance you could put up the files?

Kind regards,

Graham.

**Comment by zachary-kuhn** [comment]
Graham, thank you so much for the notice! I didn't push up the commit I had laying around, but it's up here now. Sorry for not having it here earlier!

**Comment by gburrows** [comment]
Not a problem Zach, thank <i>you</i> for creating a great set of tutorials.

Very much looking forward to the next instalment.

**Comment by gburrows** [comment]
Sorry to message again, hope you can help. The app doesn't seem to load for me (in Chrome).

It shows the React DOM tree (through React dev tools) and comes up with these console errors:

Warning: React.render is deprecated. Please use ReactDOM.render from require('react-dom') instead.
Uncaught ReferenceError: React is not defined

Changing to ReactDOM does stop that error, but I'm not sure how to make it so it knows React is defined. Couldn't find a solution online unfortunately.
